[package]
authors = ["Nathan Musoke <nathan.musoke@gmail.com>"]
name = "e2e-types"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
rand = "0.3.16"
serde = "1.0.9"
serde_derive = "1.0.9"

[dev-dependencies]
serde_json = "1.0.9"
